title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          author:
            type: text
            width: 1/2
            required: true
          year:
            type: number
            width: 1/2
          category:
            type: text
            width: 1/2
          link:
            type: url
            width: 1/2
          description:
            label: Project description
            type: textarea
            required: true
          tags:
            label: Tags
            type: tags
          date:
            num: date
            field: date
            sort: flip
            default: now
          time:
            num: time
            field: time
            sort: flip
            default: now
  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        template: gallery-image
        info: "{{ file.dimensions }}"
